version: '2'
services:
  dev: &base
    build: .
    image: keboola/gymbeam-recombee
    volumes:
      - ./:/code
      - ./data:/data
  xdebug:
    <<: *base
    build:
      context: docker/xdebug
